spring:
  application:
    name: superprof

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/superprof_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    sql:
      init:
        mode: always
        platform: mysql
    defer-datasource-initialization: true

pedro:
  vars:
    jwtSecret: ======================Pedro=APP=in=Spring===========================
    jwtExpirationMs: 86400000


# Produccion: Liquibase y Flyway

## Configuración de H2
#spring:
#  datasource:
#    url: jdbc:h2:mem:db_superprof
#    driverClassName: org.h2.Driver
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
